export const tweets = [
  {
    tweetAvatar: "tweet-profile-photo.png",
    tweetAuthor: "CNN",
    tweetAuthorUsername: "CNN",
    isCertified: true,
    tweetText:
      'President Joe Biden touted a new agreement reached with the European Union to ease Trump-era tariffs on aluminun and steel as a "major breakthrough" that would serve to both strengthen the US steek industry and combat the global climate crisis.',
    tweetImage: null,
    tweetAction: [
      { name: "message", count: 57 },
      { name: "repost", count: 144 },
      { name: "like", count: 184 },
      { name: "share" },
    ],
    date: "2023-11-26T05:00:00.723Z",
  },
  {
    tweetAvatar: "new_york_times.png",
    tweetAuthor: "The New York Times",
    tweetAuthorUsername: "nytimes",
    isCertified: true,
    tweetText:
      "Gardening boomed during the pandemic. Six Black writers share how has helped them re-establish, and reimaginem a connection to cultivation and the land",
    tweetImage: "tweet-image.png",
    tweetAction: [
      { name: "message", count: 19 },
      { name: "repost", count: 48 },
      { name: "like", count: 482 },
      { name: "share" },
    ],
    date: "2023-11-26T04:54:22.723Z",
  },
  {
    tweetAvatar: "twitter_logo.png",
    tweetAuthor: "Twitter",
    tweetAuthorUsername: "Twitter",
    isCertified: true,
    tweetText: "BIG NEWS lol jk still Twitter",
    tweetImage: null,
    tweetAction: [
      { name: "message", count: 6800 },
      { name: "repost", count: 36600 },
      { name: "like", count: 267100 },
      { name: "share" },
    ],
    date: "2023-10-23T16:20:21.723Z",
  },
  {
    tweetAvatar: "twitter_logo.png",
    tweetAuthor: "Twitter",
    tweetAuthorUsername: "Twitter",
    isCertified: true,
    tweetText: "hello literally everyone",
    tweetImage: null,
    tweetAction: [
      { name: "message", count: 108700 },
      { name: "repost", count: 785400 },
      { name: "like", count: 3300000 },
      { name: "share" },
    ],
    date: "2023-10-04T20:18:51.723Z",
  },
  {
    tweetAvatar: "RudByLnY_400x400.jpg",
    tweetAuthor: "MKADIMART",
    tweetAuthorUsername: "mkadimart",
    isCertified: true,
    tweetText: null,
    tweetImage: "F_eVAZjW4AAPpBc.jpg",
    tweetAction: [
      { name: "message", count: 81 },
      { name: "repost", count: 89 },
      { name: "like", count: 383 },
      { name: "share" },
    ],
    date: "2023-11-23T18:15:22.723Z",
  },{
    tweetAvatar: "RudByLnY_400x400.jpg",
    tweetAuthor: "av",
    tweetAuthorUsername: "ffllf",
    isCertified: true,
    tweetText: 'sdjkvnsfm dklfvofnkmvs dkl',
    tweetImage: null,
    tweetAction: [
      { name: "message", count: 81 },
      { name: "repost", count: 89 },
      { name: "like", count: 383 },
      { name: "share" },
    ],
    date: "2021-03-26T04:54:22.723Z",
  },
];
